/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokosepatu.view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import tokosepatu.modul.kasir.Transaksi;

/**
 *
 * @author asusl
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
//        setExtendedState(JFrame.MAXIMIZED_HORIZ);
//        setVisible(true);
//        setResizable(false);
    }
    
    Transaksi trans = new Transaksi();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSetting = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboardPanel = new javax.swing.JPanel();
        panelTitle = new javax.swing.JLabel();
        orderPanel = new javax.swing.JPanel();
        panelTitle1 = new javax.swing.JLabel();
        productPanel = new javax.swing.JPanel();
        panelTitle2 = new javax.swing.JLabel();
        karyawanPanel = new javax.swing.JPanel();
        panelTitle3 = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        panelTitle4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        bodyPanel.setBackground(new java.awt.Color(241, 245, 249));
        bodyPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        bodyPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(255, 255, 255));
        sidePane.setMaximumSize(new java.awt.Dimension(320, 1080));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setBackground(new java.awt.Color(147, 197, 253));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(3, 13, 69));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Graph.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setIconTextGap(16);
        btnDashboard.setPreferredSize(new java.awt.Dimension(180, 36));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        sidePane.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 300, 90));

        btnOrder.setBackground(new java.awt.Color(147, 197, 253));
        btnOrder.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(3, 13, 69));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Drawer-Done.png"))); // NOI18N
        btnOrder.setText("Orderan");
        btnOrder.setBorder(null);
        btnOrder.setIconTextGap(16);
        btnOrder.setPreferredSize(new java.awt.Dimension(180, 36));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        sidePane.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, 90));

        btnProduk.setBackground(new java.awt.Color(147, 197, 253));
        btnProduk.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnProduk.setForeground(new java.awt.Color(3, 13, 69));
        btnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Lables.png"))); // NOI18N
        btnProduk.setText("Produk");
        btnProduk.setBorder(null);
        btnProduk.setIconTextGap(16);
        btnProduk.setPreferredSize(new java.awt.Dimension(180, 36));
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });
        sidePane.add(btnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 300, 90));

        btnKaryawan.setBackground(new java.awt.Color(147, 197, 253));
        btnKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnKaryawan.setForeground(new java.awt.Color(3, 13, 69));
        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Users.png"))); // NOI18N
        btnKaryawan.setText("Karyawan");
        btnKaryawan.setBorder(null);
        btnKaryawan.setIconTextGap(16);
        btnKaryawan.setPreferredSize(new java.awt.Dimension(180, 36));
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });
        sidePane.add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 300, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("OTHER");
        sidePane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, -1, -1));

        btnSetting.setBackground(new java.awt.Color(147, 197, 253));
        btnSetting.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(3, 13, 69));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Setting-1.png"))); // NOI18N
        btnSetting.setText("Pengaturan");
        btnSetting.setBorder(null);
        btnSetting.setIconTextGap(16);
        btnSetting.setPreferredSize(new java.awt.Dimension(180, 36));
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        sidePane.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 300, 90));

        bodyPanel.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 1080));

        jTabbedPane1.setBackground(new java.awt.Color(241, 245, 249));

        dashboardPanel.setBackground(new java.awt.Color(241, 245, 249));

        panelTitle.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        panelTitle.setText("Dashboard");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panelTitle)
                .addContainerGap(1362, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelTitle)
                .addContainerGap(988, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard", dashboardPanel);

        orderPanel.setBackground(new java.awt.Color(241, 245, 249));

        panelTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelTitle1.setText("Orderan");

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panelTitle1)
                .addContainerGap(1389, Short.MAX_VALUE))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelTitle1)
                .addContainerGap(983, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Orderan", orderPanel);

        productPanel.setBackground(new java.awt.Color(241, 245, 249));

        panelTitle2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        panelTitle2.setText("Data Produk");

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panelTitle2)
                .addContainerGap(1337, Short.MAX_VALUE))
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelTitle2)
                .addContainerGap(988, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produk", productPanel);

        karyawanPanel.setBackground(new java.awt.Color(241, 245, 249));

        panelTitle3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        panelTitle3.setText("Data Karyawan");

        javax.swing.GroupLayout karyawanPanelLayout = new javax.swing.GroupLayout(karyawanPanel);
        karyawanPanel.setLayout(karyawanPanelLayout);
        karyawanPanelLayout.setHorizontalGroup(
            karyawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panelTitle3)
                .addContainerGap(1300, Short.MAX_VALUE))
        );
        karyawanPanelLayout.setVerticalGroup(
            karyawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelTitle3)
                .addContainerGap(988, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Karyawan", karyawanPanel);

        settingPanel.setBackground(new java.awt.Color(241, 245, 249));

        panelTitle4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        panelTitle4.setText("Pengaturan");

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panelTitle4)
                .addContainerGap(1353, Short.MAX_VALUE))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelTitle4)
                .addContainerGap(988, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pengaturan", settingPanel);

        bodyPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -70, 1570, 1150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        setActiveColor(btnDashboard);
        resetColor(btnOrder);
        resetColor(btnProduk);
        resetColor(btnKaryawan);
        resetColor(btnSetting);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        // TODO add your handling code here:
        resetColor(btnDashboard);
        resetColor(btnOrder);
        setActiveColor(btnProduk);
        resetColor(btnKaryawan);
        resetColor(btnSetting);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        // TODO add your handling code here:
        resetColor(btnDashboard);
        resetColor(btnOrder);
        resetColor(btnProduk);
        setActiveColor(btnKaryawan);
        resetColor(btnSetting);
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        resetColor(btnDashboard);
        resetColor(btnOrder);
        resetColor(btnProduk);
        resetColor(btnKaryawan);
        setActiveColor(btnSetting);
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        resetColor(btnDashboard);
        setActiveColor(btnOrder);
        resetColor(btnProduk);
        resetColor(btnKaryawan);
        resetColor(btnSetting);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnOrderActionPerformed
    
    void setActiveColor(JButton button) {
        button.setBackground(new Color(59,130,246));
        button.setForeground(new Color(255,255,255));
    }
    
    void resetColor(JButton button) {
        button.setBackground(new Color(147,197,253));
        button.setForeground(new Color(3,13,69));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnSetting;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel karyawanPanel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JLabel panelTitle;
    private javax.swing.JLabel panelTitle1;
    private javax.swing.JLabel panelTitle2;
    private javax.swing.JLabel panelTitle3;
    private javax.swing.JLabel panelTitle4;
    private javax.swing.JPanel productPanel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables
}
