/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokosepatu.modul.barang;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author ASUS
 */
public class addBarang extends javax.swing.JFrame {

    /**
     * Creates new form tambahbarang
     */
    public addBarang() {
        initComponents();

        selectMerk();
        selectKategori();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createOrderPanel = new javax.swing.JPanel();
        panelTitle1 = new javax.swing.JLabel();
        btnNewOrder = new javax.swing.JButton();
        qtyLabel2 = new javax.swing.JLabel();
        labelProduk1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTambah1 = new javax.swing.JButton();
        btnTambah2 = new javax.swing.JButton();
        qtyLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        qtyLabel5 = new javax.swing.JLabel();
        qtyLabel9 = new javax.swing.JLabel();
        qtyLabel10 = new javax.swing.JLabel();
        txtHargabeli = new javax.swing.JTextField();
        qtyLabel11 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        jComboBoxMerk = new javax.swing.JComboBox<>();
        txtNamabarang = new javax.swing.JTextField();
        qtyLabel12 = new javax.swing.JLabel();
        txtHargajual = new javax.swing.JTextField();
        qtyLabel13 = new javax.swing.JLabel();
        jComboBoxKategori = new javax.swing.JComboBox<>();
        txtukuran = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createOrderPanel.setBackground(new java.awt.Color(241, 245, 249));
        createOrderPanel.setPreferredSize(new java.awt.Dimension(852, 600));

        panelTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelTitle1.setText("Tambah Barang");

        btnNewOrder.setBackground(new java.awt.Color(59, 130, 246));
        btnNewOrder.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnNewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnNewOrder.setText("Buat Orderan");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        qtyLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel2.setText("NAMA BARANG");

        labelProduk1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelProduk1.setText("BAGIAN");

        btnSimpan.setBackground(new java.awt.Color(59, 130, 246));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTambah1.setBackground(new java.awt.Color(59, 130, 246));
        btnTambah1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTambah1.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah1.setText("TAMBAH");
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        btnTambah2.setBackground(new java.awt.Color(59, 130, 246));
        btnTambah2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTambah2.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah2.setText("TAMBAH");
        btnTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah2ActionPerformed(evt);
            }
        });

        qtyLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel3.setText("ID BARANG");

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtid.setToolTipText("");
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        qtyLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel5.setText("MERK");

        qtyLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel9.setText("KATEGORI");

        qtyLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel10.setText("HARGA BELI");

        txtHargabeli.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtHargabeli.setToolTipText("");
        txtHargabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargabeliActionPerformed(evt);
            }
        });

        qtyLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel11.setText("KETERANGAN");

        txtKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtKeterangan.setToolTipText("");
        txtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganActionPerformed(evt);
            }
        });

        txtNamabarang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtNamabarang.setToolTipText("");
        txtNamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamabarangActionPerformed(evt);
            }
        });

        qtyLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel12.setText("HARGA JUAL");

        txtHargajual.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtHargajual.setToolTipText("");
        txtHargajual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargajualActionPerformed(evt);
            }
        });

        qtyLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel13.setText("UKURAN");

        txtukuran.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtukuran.setToolTipText("");
        txtukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtukuranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createOrderPanelLayout = new javax.swing.GroupLayout(createOrderPanel);
        createOrderPanel.setLayout(createOrderPanelLayout);
        createOrderPanelLayout.setHorizontalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addComponent(panelTitle1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createOrderPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                                        .addComponent(labelProduk1)
                                        .addGap(547, 547, 547)
                                        .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(qtyLabel2)
                                            .addComponent(qtyLabel3)
                                            .addComponent(qtyLabel5)
                                            .addComponent(qtyLabel9)
                                            .addComponent(qtyLabel10)
                                            .addComponent(qtyLabel11)
                                            .addComponent(qtyLabel13)
                                            .addComponent(qtyLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNamabarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxMerk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHargabeli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtKeterangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHargajual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxKategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtukuran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8)))
                        .addGap(0, 71, Short.MAX_VALUE))))
        );
        createOrderPanelLayout.setVerticalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                        .addComponent(qtyLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(qtyLabel2)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addComponent(jComboBoxMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                        .addComponent(qtyLabel5)
                        .addGap(18, 18, 18)))
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qtyLabel13)
                    .addComponent(txtukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel10))
                .addGap(18, 18, 18)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel12))
                .addGap(18, 18, 18)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel11))
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291)
                        .addComponent(btnTambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245)
                        .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                        .addGap(950, 950, 950)
                        .addComponent(labelProduk1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectMerk() {
        try {
            Statement statement = (Statement) Koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM tb_merk");
            while (res.next()) {
                jComboBoxMerk.addItem(res.getInt("id") + " - " + res.getString("merk"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }
    
    private void selectKategori() {
        try {
            Statement statement = (Statement) Koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM tb_kategori");
            while (res.next()) {
                jComboBoxKategori.addItem(res.getInt("id") + " - " + res.getString("kategori"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed

    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement("insert into tb_barang(id, nama_barang, id_merk, id_kategori, ukuran, harga_beli, harga_jual, keterangan) values(?,?,?,?,?,?,?,?)");

            stmt.setString(1, txtid.getText());
            stmt.setString(2, txtNamabarang.getText());

            String[] merk = jComboBoxMerk.getSelectedItem().toString().split(" - ");
            int idMerk = Integer.parseInt(merk[0]);
            stmt.setInt(3, idMerk);
            
            String[] kategori = jComboBoxKategori.getSelectedItem().toString().split(" - ");
            int idKategori = Integer.parseInt(kategori[0]);
            stmt.setInt(4, idKategori);
            
            int ukuran = Integer.parseInt(txtukuran.getText());
            stmt.setInt(5, ukuran);

            double harga_beli = Double.parseDouble(txtHargabeli.getText());
            stmt.setDouble(6, harga_beli);
            
            double harga_jual = Double.parseDouble(txtHargajual.getText());
            stmt.setDouble(7, harga_jual);
            
            stmt.setString(8, txtKeterangan.getText());

            stmt.executeUpdate();
            setVisible(false);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            stokbarang brg = new stokbarang();
            brg.setVisible(true);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah2ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtHargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargabeliActionPerformed

    private void txtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeteranganActionPerformed

    private void txtNamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamabarangActionPerformed

    private void txtHargajualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargajualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargajualActionPerformed

    private void txtukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtukuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtukuranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JButton btnTambah2;
    private javax.swing.JPanel createOrderPanel;
    private javax.swing.JComboBox<String> jComboBoxKategori;
    private javax.swing.JComboBox<String> jComboBoxMerk;
    private javax.swing.JLabel labelProduk1;
    private javax.swing.JLabel panelTitle1;
    private javax.swing.JLabel qtyLabel10;
    private javax.swing.JLabel qtyLabel11;
    private javax.swing.JLabel qtyLabel12;
    private javax.swing.JLabel qtyLabel13;
    private javax.swing.JLabel qtyLabel2;
    private javax.swing.JLabel qtyLabel3;
    private javax.swing.JLabel qtyLabel5;
    private javax.swing.JLabel qtyLabel9;
    private javax.swing.JTextField txtHargabeli;
    private javax.swing.JTextField txtHargajual;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNamabarang;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtukuran;
    // End of variables declaration//GEN-END:variables
}
