/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokosepatu.main;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import tokosepatu.auth.Login;
import tokosepatu.auth.session;
import tokosepatu.modul.barang.stokbarang;
import tokosepatu.modul.karyawan.Karyawan;
import tokosepatu.modul.karyawan.tableUser;
import tokosepatu.modul.kasir.Transaksi;

/**
 *
 * @author asusl
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        username.setText(session.getNamaKaryawan());
        cekLevel();
    }

    Transaksi trans = new Transaksi();
    Karyawan kry = new Karyawan();
    stokbarang brg = new stokbarang();
    tableUser users = new tableUser();

    private void cekSession() {
        if (session.getUsername().isEmpty()) {
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }

    private void cekLevel() {
        int level = 0;
        /* 1 -> Admin
           2 -> Kasir
           3 -> Barang
         */

        try {
            Statement statement = (Statement) Koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT level FROM tb_users WHERE username = '" + session.getUsername() + "'");
            while (res.next()) {
                level = res.getInt("level");
                if (level == 2) {
                    btnProduk.setVisible(false);
                    btnKaryawan.setVisible(false);
                } else if (level == 3) {

                    btnOrder.setVisible(false);
                    btnKaryawan.setVisible(false);
                }
//                else {
//                    btnDashboard.setVisible(false);
//                    btnOrder.setVisible(false);
//                    btnProduk.setVisible(false);
//                    btnKaryawan.setVisible(false);
//                    jLabel1.setVisible(false);
//                    btnSetting.setVisible(false);
//                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void setActiveColor(JButton button) {
        button.setBackground(new Color(59, 130, 246));
        button.setForeground(new Color(255, 255, 255));
    }

    void resetColor(JButton button) {
        button.setBackground(new Color(147, 197, 253));
        button.setForeground(new Color(3, 13, 69));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        greetings = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnUsers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(165, 180, 252));

        jPanel1.setBackground(new java.awt.Color(238, 242, 255));

        btnOrder.setBackground(new java.awt.Color(147, 197, 253));
        btnOrder.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(3, 13, 69));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Drawer-Done.png"))); // NOI18N
        btnOrder.setText("Orderan");
        btnOrder.setBorder(null);
        btnOrder.setIconTextGap(16);
        btnOrder.setPreferredSize(new java.awt.Dimension(180, 36));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnProduk.setBackground(new java.awt.Color(147, 197, 253));
        btnProduk.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnProduk.setForeground(new java.awt.Color(3, 13, 69));
        btnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Lables.png"))); // NOI18N
        btnProduk.setText("Produk");
        btnProduk.setBorder(null);
        btnProduk.setIconTextGap(16);
        btnProduk.setPreferredSize(new java.awt.Dimension(180, 36));
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        btnKaryawan.setBackground(new java.awt.Color(147, 197, 253));
        btnKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnKaryawan.setForeground(new java.awt.Color(3, 13, 69));
        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Users.png"))); // NOI18N
        btnKaryawan.setText("Karyawan");
        btnKaryawan.setBorder(null);
        btnKaryawan.setIconTextGap(16);
        btnKaryawan.setPreferredSize(new java.awt.Dimension(180, 36));
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(185, 28, 28));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Logout.png"))); // NOI18N
        btnLogout.setText("Keluar");
        btnLogout.setBorder(null);
        btnLogout.setIconTextGap(16);
        btnLogout.setPreferredSize(new java.awt.Dimension(180, 36));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        greetings.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        greetings.setText("Welcome Back, ");

        username.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        username.setText("name");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Footy");
        jLabel1.setIconTextGap(8);

        btnUsers.setBackground(new java.awt.Color(147, 197, 253));
        btnUsers.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(3, 13, 69));
        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/Users.png"))); // NOI18N
        btnUsers.setText("Users");
        btnUsers.setBorder(null);
        btnUsers.setIconTextGap(16);
        btnUsers.setPreferredSize(new java.awt.Dimension(180, 36));
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel1))
                            .addComponent(greetings, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greetings)
                    .addComponent(username))
                .addGap(26, 26, 26)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        setActiveColor(btnOrder);
        resetColor(btnProduk);
        resetColor(btnKaryawan);
        trans.setVisible(true);
        trans.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        // TODO add your handling code here:
        resetColor(btnOrder);
        setActiveColor(btnProduk);
        resetColor(btnKaryawan);
        brg.setVisible(true);
        brg.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        // TODO add your handling code here:
        resetColor(btnOrder);
        resetColor(btnProduk);
        setActiveColor(btnKaryawan);
        kry.setVisible(true);
        kry.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Logout?");
        switch (option) {
            case JOptionPane.YES_OPTION:
            try {
                if (!session.getUsername().isEmpty()) {
                    session.setUsername(null);
                    this.dispose();
                    Login login = new Login();
                    login.setVisible(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        resetColor(btnOrder);
        resetColor(btnProduk);
        resetColor(btnKaryawan);
        setActiveColor(btnUsers);
        users.setVisible(true);
        users.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel greetings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
