/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokosepatu.modul.kasir;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author asusl
 */
public class EditOrder extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public EditOrder() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
        
        selectProduct();
    }
    
    double harga_barang;
    
    private void selectProduct() {
        try {
            Statement statement = (Statement) Koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM tb_barang");
            while (res.next()) {
                harga_barang = res.getDouble("harga");
                produkSelect.addItem(res.getString("id").toUpperCase() + " - " + res.getString("nama_barang"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editOrderPanel = new javax.swing.JPanel();
        panelTitle1 = new javax.swing.JLabel();
        idField = new javax.swing.JLabel();
        btnUpdateOrder = new javax.swing.JButton();
        labelProduk = new javax.swing.JLabel();
        produkSelect = new javax.swing.JComboBox<>();
        qtyLabel = new javax.swing.JLabel();
        qtyField = new javax.swing.JTextField();
        metodeBayar = new javax.swing.JLabel();
        metodeBayarSelect = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editOrderPanel.setBackground(new java.awt.Color(241, 245, 249));
        editOrderPanel.setPreferredSize(new java.awt.Dimension(852, 600));

        panelTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelTitle1.setText("Edit Orderan");

        idField.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        idField.setText("idTransaksi");
        idField.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnUpdateOrder.setBackground(new java.awt.Color(59, 130, 246));
        btnUpdateOrder.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnUpdateOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateOrder.setText("Simpan");
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderActionPerformed(evt);
            }
        });

        labelProduk.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelProduk.setText("Produk");

        produkSelect.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        produkSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkSelectActionPerformed(evt);
            }
        });

        qtyLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel.setText("Jumlah");

        qtyField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyField.setToolTipText("");
        qtyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyFieldActionPerformed(evt);
            }
        });

        metodeBayar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        metodeBayar.setText("Metode Pembayaran");

        metodeBayarSelect.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        metodeBayarSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Dana", "ShopeePay", "Link Aja", "Gopay" }));
        metodeBayarSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodeBayarSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editOrderPanelLayout = new javax.swing.GroupLayout(editOrderPanel);
        editOrderPanel.setLayout(editOrderPanelLayout);
        editOrderPanelLayout.setHorizontalGroup(
            editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editOrderPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editOrderPanelLayout.createSequentialGroup()
                        .addComponent(panelTitle1)
                        .addGap(459, 459, 459)
                        .addComponent(idField))
                    .addGroup(editOrderPanelLayout.createSequentialGroup()
                        .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(qtyLabel)
                                .addComponent(labelProduk))
                            .addGroup(editOrderPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(metodeBayar)))
                        .addGap(40, 40, 40)
                        .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(metodeBayarSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnUpdateOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(produkSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        editOrderPanelLayout.setVerticalGroup(
            editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editOrderPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelTitle1)
                    .addComponent(idField))
                .addGap(103, 103, 103)
                .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProduk)
                    .addComponent(produkSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel))
                .addGap(41, 41, 41)
                .addGroup(editOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metodeBayarSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metodeBayar))
                .addGap(35, 35, 35)
                .addComponent(btnUpdateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderActionPerformed
        // TODO add your handling code here:
        int idTransaksi = Integer.parseInt(idField.getText());
        System.out.println(idTransaksi);
        
        String oldProduk = (String) produkSelect.getSelectedItem();
        System.out.println(oldProduk);
        String[] produk = oldProduk.split(" - ");
        String idProduk = produk[0].toLowerCase();
        
        int qty = Integer.parseInt(qtyField.getText());
        
        double total_bayar = qty * harga_barang;
        System.out.println(total_bayar);
        
        int metode = 0;
        String selectedMetode = (String) metodeBayarSelect.getSelectedItem();
        System.out.println(selectedMetode);
        if (selectedMetode == "Cash") {
            metode = 1;
        } else if (selectedMetode == "Dana") {
            metode = 2;
        } else if (selectedMetode == "ShopeePay") {
            metode = 3;
        } else if (selectedMetode == "Link Aja") {
            metode = 4;
        } else if (selectedMetode == "Gopay") {
            metode = 5;
        }
        
        try {
            String sql = "UPDATE tb_transaksi SET "
                    + "id_barang = '" + idProduk + "'"
                    + ", qty = " + qty
                    + ", total_bayar = " + total_bayar
                    + ", metode_pembayaran = " + metode
                    + " WHERE id = " + idTransaksi;
            
            java.sql.Connection conn;
            conn = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit data successfully");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateOrderActionPerformed

    private void produkSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produkSelectActionPerformed

    private void qtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyFieldActionPerformed

    private void metodeBayarSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodeBayarSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodeBayarSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JPanel editOrderPanel;
    public javax.swing.JLabel idField;
    private javax.swing.JLabel labelProduk;
    private javax.swing.JLabel metodeBayar;
    public javax.swing.JComboBox<String> metodeBayarSelect;
    private javax.swing.JLabel panelTitle1;
    public javax.swing.JComboBox<String> produkSelect;
    public javax.swing.JTextField qtyField;
    private javax.swing.JLabel qtyLabel;
    // End of variables declaration//GEN-END:variables
}
