/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokosepatu.modul.kasir;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author asusl
 */
public class FormBayar extends javax.swing.JFrame {

    /**
     * Creates new form FormBayar
     */
    public FormBayar() {
        initComponents();
    }

    public static String currencyID(double nominal) {
        Locale localeID = new Locale("in", "ID");
        NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(localeID);
        return formatRupiah.format((double) nominal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formBayarPanel = new javax.swing.JPanel();
        panelTitle1 = new javax.swing.JLabel();
        totalBayarLabel = new javax.swing.JLabel();
        totalBayar = new javax.swing.JLabel();
        jumlahBayarLabel = new javax.swing.JLabel();
        jumlahBayarField = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        idTransaksiField = new javax.swing.JTextField();
        idTransaksiLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formBayarPanel.setBackground(new java.awt.Color(241, 245, 249));
        formBayarPanel.setPreferredSize(new java.awt.Dimension(852, 600));

        panelTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelTitle1.setText("Rincian Pembayaran");

        totalBayarLabel.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        totalBayarLabel.setText("Total Bayar");

        totalBayar.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        totalBayar.setText("0");

        jumlahBayarLabel.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jumlahBayarLabel.setText("Jumlah Bayar");

        jumlahBayarField.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jumlahBayarField.setToolTipText("");
        jumlahBayarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahBayarFieldActionPerformed(evt);
            }
        });

        btnPay.setBackground(new java.awt.Color(59, 130, 246));
        btnPay.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Bayar");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        idTransaksiField.setEditable(false);
        idTransaksiField.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        idTransaksiField.setToolTipText("");

        idTransaksiLabel.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        idTransaksiLabel.setText("ID Transaksi");

        javax.swing.GroupLayout formBayarPanelLayout = new javax.swing.GroupLayout(formBayarPanel);
        formBayarPanel.setLayout(formBayarPanelLayout);
        formBayarPanelLayout.setHorizontalGroup(
            formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBayarPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBayarPanelLayout.createSequentialGroup()
                        .addComponent(panelTitle1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formBayarPanelLayout.createSequentialGroup()
                        .addGroup(formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(formBayarPanelLayout.createSequentialGroup()
                                    .addComponent(jumlahBayarLabel)
                                    .addGap(112, 112, 112)
                                    .addComponent(jumlahBayarField, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                                .addGroup(formBayarPanelLayout.createSequentialGroup()
                                    .addGroup(formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(totalBayarLabel)
                                        .addComponent(idTransaksiLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(idTransaksiField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                        .addComponent(totalBayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 51, Short.MAX_VALUE))))
        );
        formBayarPanelLayout.setVerticalGroup(
            formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBayarPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTransaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTransaksiLabel))
                .addGap(15, 15, 15)
                .addGroup(formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBayarLabel)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formBayarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBayarLabel))
                .addGap(18, 18, 18)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formBayarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formBayarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahBayarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahBayarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahBayarFieldActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        Kasir kasir = new Kasir();

        String idTransaksi = idTransaksiField.getText();

        String bayar = totalBayar.getText().replace(".", "").replace(",00", "");
        String[] tot = bayar.split("Rp");

        Double total = Double.parseDouble(tot[1]);
        Double jmlBayar = Double.parseDouble(jumlahBayarField.getText());

        Double kembalian = jmlBayar - total;
        if (jmlBayar < total) {
            JOptionPane.showMessageDialog(this, "Uang yang dibayarkan kurang");
        } else if (jmlBayar == total) {
            JOptionPane.showMessageDialog(this, "Uang yang dibayarkan pas");
            try {
                String sql = "UPDATE tb_transaksi SET status = " + 2 + " WHERE id = '" + idTransaksi + "'";

                java.sql.Connection conn;
                conn = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                Transaksi trans = new Transaksi();
                kasir.setVisible(false);
                trans.setVisible(true);
//            JOptionPane.showMessageDialog(null, "Edit data successfully");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            this.dispose();
            kasir.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Uang kembalian " + currencyID(kembalian));
            try {
                String sql = "UPDATE tb_transaksi SET status = " + 2 + " WHERE id = '" + idTransaksi + "'";

                java.sql.Connection conn;
                conn = (Connection) Koneksi.getConnection();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                Transaksi trans = new Transaksi();
                kasir.setVisible(false);
                trans.setVisible(true);
//            JOptionPane.showMessageDialog(null, "Edit data successfully");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            this.dispose();
            kasir.setVisible(false);
        }
    }//GEN-LAST:event_btnPayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPay;
    private javax.swing.JPanel formBayarPanel;
    public javax.swing.JTextField idTransaksiField;
    private javax.swing.JLabel idTransaksiLabel;
    private javax.swing.JTextField jumlahBayarField;
    private javax.swing.JLabel jumlahBayarLabel;
    private javax.swing.JLabel panelTitle1;
    public javax.swing.JLabel totalBayar;
    private javax.swing.JLabel totalBayarLabel;
    // End of variables declaration//GEN-END:variables
}
