/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokosepatu.modul.kasir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.UUID;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import static jdk.nashorn.internal.runtime.Debug.id;
import koneksi.Koneksi;

/**
 *
 * @author asusl
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();

        selectProduct();
        setJTableColumnsWidth(cartTable, 480, 40, 10, 20);
    }

    public static String currencyID(double nominal) {
        Locale localeID = new Locale("in", "ID");
        NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(localeID);
        return formatRupiah.format((double) nominal);
    }

    private void selectProduct() {
        try {
            Statement statement = (Statement) Koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT id, nama_barang, harga_jual FROM tb_barang");
            while (res.next()) {
                produkSelect.addItem(res.getString("id").toUpperCase() + " - " + res.getString("nama_barang") + " - " + res.getDouble("harga_jual"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    public static void setJTableColumnsWidth(JTable table, int tablePreferredWidth,
            double... percentages) {
        double total = 0;
        for (int i = 0; i < table.getColumnModel().getColumnCount(); i++) {
            total += percentages[i];
        }

        for (int i = 0; i < table.getColumnModel().getColumnCount(); i++) {
            TableColumn column = table.getColumnModel().getColumn(i);
            column.setPreferredWidth((int) (tablePreferredWidth * (percentages[i] / total)));
        }
    }

    public void countTotal() {
        FormBayar pay = new FormBayar();
        int numRow = cartTable.getRowCount();

//        int diskon = 0;
//        diskon = Integer.parseInt(diskonField.getText());
        double total = 0;

        for (int i = 0; i < numRow; i++) {
            double val = Double.valueOf(cartTable.getValueAt(i, 2).toString());
            total += val;
        }

//        if (diskon != 0) {
//            double potongan = total * (diskon / 100);
//            total += potongan;
//        }
        totalBayarField.setText(currencyID(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mainPanel = new javax.swing.JPanel();
        productPanel = new javax.swing.JPanel();
        labelProduk = new javax.swing.JLabel();
        produkSelect = new javax.swing.JComboBox<>();
        qtyLabel = new javax.swing.JLabel();
        qtyField = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        panelTitle1 = new javax.swing.JLabel();
        billPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        diskonField = new javax.swing.JTextField();
        diskonLabel = new javax.swing.JLabel();
        totalBayarLabel = new javax.swing.JLabel();
        totalBayarField = new javax.swing.JLabel();
        metodeBayar = new javax.swing.JLabel();
        metodeBayarSelect = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnBilling = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(245, 245, 245));

        productPanel.setBackground(new java.awt.Color(214, 211, 209));

        labelProduk.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelProduk.setText("Produk");

        produkSelect.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        produkSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkSelectActionPerformed(evt);
            }
        });

        qtyLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel.setText("Jumlah");

        qtyField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyField.setToolTipText("");
        qtyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyFieldActionPerformed(evt);
            }
        });

        btnAddItem.setBackground(new java.awt.Color(59, 130, 246));
        btnAddItem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(255, 255, 255));
        btnAddItem.setText("Tambah");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        panelTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelTitle1.setText("Buat Orderan");

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTitle1)
                        .addGroup(productPanelLayout.createSequentialGroup()
                            .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(qtyLabel)
                                .addComponent(labelProduk))
                            .addGap(161, 161, 161)
                            .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(qtyField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(produkSelect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panelTitle1)
                .addGap(39, 39, 39)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProduk)
                    .addComponent(produkSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel))
                .addGap(18, 18, 18)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        billPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 13, 69));
        jLabel1.setText("Bills");

        cartTable.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Produk", "Qty", "Harga"
            }
        ));
        cartTable.setRowHeight(52);
        jScrollPane1.setViewportView(cartTable);

        diskonField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        diskonField.setToolTipText("");
        diskonField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonFieldActionPerformed(evt);
            }
        });

        diskonLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        diskonLabel.setText("Diskon");

        totalBayarLabel.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        totalBayarLabel.setText("Total Bayar");

        totalBayarField.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        totalBayarField.setText("0");

        metodeBayar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        metodeBayar.setText("Metode Pembayaran");

        metodeBayarSelect.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        metodeBayarSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Dana", "ShopeePay", "Link Aja", "Gopay" }));

        btnBilling.setBackground(new java.awt.Color(37, 99, 235));
        btnBilling.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        btnBilling.setForeground(new java.awt.Color(255, 255, 255));
        btnBilling.setText("Buat Bill");
        btnBilling.setBorder(null);
        btnBilling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBilling.setIconTextGap(16);
        btnBilling.setPreferredSize(new java.awt.Dimension(180, 36));
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(255, 0, 0));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokosepatu/images/outline/minus.png"))); // NOI18N
        btnRemove.setBorder(null);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addComponent(metodeBayar)
                        .addGap(47, 47, 47)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(billPanelLayout.createSequentialGroup()
                                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalBayarLabel)
                                    .addComponent(diskonLabel))
                                .addGap(72, 72, 72)
                                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(diskonField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(totalBayarField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(metodeBayarSelect, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnBilling, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskonField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diskonLabel))
                .addGap(27, 27, 27)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBayarLabel)
                    .addComponent(totalBayarField))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metodeBayar)
                    .addComponent(metodeBayarSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(productPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(billPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void produkSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produkSelectActionPerformed

    private void qtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyFieldActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) cartTable.getModel();
        List list = new ArrayList<>();
        cartTable.setAutoCreateColumnsFromModel(true);

        String[] value = produkSelect.getSelectedItem().toString().split(" - ");
        String produk = value[0] + " - " + value[1];

        Double harga = Double.parseDouble(value[2]);

        int qty = Integer.parseInt(qtyField.getText());
        Double hargaJual = harga * qty;

        list.add(produk);
        list.add(qty);
        list.add(hargaJual);
        dataModel.addRow(list.toArray());

        countTotal();
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void diskonFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskonFieldActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        // TODO add your handling code here:
        int numRow = cartTable.getRowCount();
        TableModel model = cartTable.getModel();
        String uniqueID = UUID.randomUUID().toString();

        String bayar = metodeBayarSelect.getSelectedItem().toString();
        int metode = 0;

        if (bayar == "Cash") {
            metode = 1;
        } else if (bayar == "Dana") {
            metode = 2;
        } else if (bayar == "ShopeePay") {
            metode = 3;
        } else if (bayar == "Link Aja") {
            metode = 4;
        } else if (bayar == "Gopay") {
            metode = 5;
        }

        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO tb_transaksi(id, id_barang, qty, total_bayar, metode_pembayaran) VALUES(?,?,?,?,?)");
            for (int i = 0; i < numRow; i++) {
                String[] produk = model.getValueAt(i, 0).toString().split(" - ");
                String idProduk = produk[0].toLowerCase();

                int qty = Integer.parseInt(model.getValueAt(i, 1).toString());
                double harga = Double.parseDouble(model.getValueAt(i, 2).toString());

                stmt.setString(1, uniqueID);
                stmt.setString(2, idProduk);
                stmt.setInt(3, qty);
                stmt.setDouble(4, harga);
                stmt.setInt(5, metode);

                stmt.executeUpdate();
            }
            FormBayar pay = new FormBayar();
            pay.totalBayar.setText(totalBayarField.getText());
            pay.idTransaksiField.setText(uniqueID);
            pay.setVisible(true);
            pay.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBillingActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) cartTable.getModel();
        if (cartTable.getSelectedRowCount() == 1) {
            tblModel.removeRow(cartTable.getSelectedRow());
            countTotal();
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billPanel;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnRemove;
    private javax.swing.JTable cartTable;
    private javax.swing.JTextField diskonField;
    private javax.swing.JLabel diskonLabel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelProduk;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel metodeBayar;
    private javax.swing.JComboBox<String> metodeBayarSelect;
    private javax.swing.JLabel panelTitle1;
    private javax.swing.JPanel productPanel;
    private javax.swing.JComboBox<String> produkSelect;
    private javax.swing.JTextField qtyField;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JLabel totalBayarField;
    private javax.swing.JLabel totalBayarLabel;
    // End of variables declaration//GEN-END:variables
}
