/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokosepatu.modul.karyawan;

/**
 *
 * @author Administrator
 */
public class detailUser extends javax.swing.JFrame {

    /**
     * Creates new form detailUser
     */
    public detailUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createOrderPanel = new javax.swing.JPanel();
        panelTitle1 = new javax.swing.JLabel();
        btnNewOrder = new javax.swing.JButton();
        labelProduk = new javax.swing.JLabel();
        qtyLabel2 = new javax.swing.JLabel();
        qtyLabel6 = new javax.swing.JLabel();
        labelProduk1 = new javax.swing.JLabel();
        btnTambah1 = new javax.swing.JButton();
        btnTambah2 = new javax.swing.JButton();
        qtyLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        qtyLabel3 = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        nik = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        jabatan = new javax.swing.JLabel();
        qtyLabel10 = new javax.swing.JLabel();
        tgllahir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createOrderPanel.setBackground(new java.awt.Color(241, 245, 249));
        createOrderPanel.setPreferredSize(new java.awt.Dimension(852, 600));

        panelTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelTitle1.setText("Details");

        btnNewOrder.setBackground(new java.awt.Color(59, 130, 246));
        btnNewOrder.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnNewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnNewOrder.setText("Buat Orderan");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        labelProduk.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelProduk.setText("JENIS KELAMIN");

        qtyLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel2.setText("NAMA");

        qtyLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel6.setText("ALAMAT");

        labelProduk1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelProduk1.setText("BAGIAN");

        btnTambah1.setBackground(new java.awt.Color(59, 130, 246));
        btnTambah1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTambah1.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah1.setText("TAMBAH");
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        btnTambah2.setBackground(new java.awt.Color(59, 130, 246));
        btnTambah2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTambah2.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah2.setText("TAMBAH");
        btnTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah2ActionPerformed(evt);
            }
        });

        qtyLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel7.setText("JABATAN");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        txtId.setText("1001");

        nama.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nama.setText("Rizky");

        qtyLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel3.setText("NIK");

        jk.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jk.setText("Pria");

        nik.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nik.setText("1234567893234567");

        alamat.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        alamat.setText("Panggoi");

        jabatan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jabatan.setText("Manager");

        qtyLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        qtyLabel10.setText("TANGGAL LAHIR");

        tgllahir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tgllahir.setText("2002/08/30");

        javax.swing.GroupLayout createOrderPanelLayout = new javax.swing.GroupLayout(createOrderPanel);
        createOrderPanel.setLayout(createOrderPanelLayout);
        createOrderPanelLayout.setHorizontalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addComponent(labelProduk1)
                        .addGap(551, 551, 551)
                        .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                                .addComponent(qtyLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nik))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                                .addComponent(qtyLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nama))
                            .addGroup(createOrderPanelLayout.createSequentialGroup()
                                .addComponent(labelProduk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jk))
                            .addGroup(createOrderPanelLayout.createSequentialGroup()
                                .addComponent(qtyLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 792, Short.MAX_VALUE)
                                .addComponent(tgllahir))
                            .addGroup(createOrderPanelLayout.createSequentialGroup()
                                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qtyLabel7)
                                    .addComponent(qtyLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jabatan, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(98, 98, 98))))
        );
        createOrderPanelLayout.setVerticalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelTitle1)
                    .addComponent(txtId))
                .addGap(36, 36, 36)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(qtyLabel2))
                .addGap(35, 35, 35)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyLabel3)
                    .addComponent(nik))
                .addGap(29, 29, 29)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyLabel10)
                    .addComponent(tgllahir))
                .addGap(30, 30, 30)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProduk)
                    .addComponent(jk))
                .addGap(34, 34, 34)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat)
                    .addComponent(qtyLabel6))
                .addGap(40, 40, 40)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jabatan)
                    .addComponent(qtyLabel7))
                .addGap(1173, 1173, 1173)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProduk1)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addGap(557, 557, 557)
                        .addComponent(btnTambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245)
                        .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(createOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(createOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed

    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JButton btnTambah2;
    private javax.swing.JPanel createOrderPanel;
    private javax.swing.JLabel jabatan;
    private javax.swing.JLabel jk;
    private javax.swing.JLabel labelProduk;
    private javax.swing.JLabel labelProduk1;
    public javax.swing.JLabel nama;
    private javax.swing.JLabel nik;
    private javax.swing.JLabel panelTitle1;
    private javax.swing.JLabel qtyLabel10;
    private javax.swing.JLabel qtyLabel2;
    private javax.swing.JLabel qtyLabel3;
    private javax.swing.JLabel qtyLabel6;
    private javax.swing.JLabel qtyLabel7;
    private javax.swing.JLabel tgllahir;
    public javax.swing.JLabel txtId;
    // End of variables declaration//GEN-END:variables
}
